apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: vaex-longhorn
  region: us-east-1
  version: "1.20"

cloudWatch:
  clusterLogging:
    enableTypes: ["all"]

managedNodeGroups:
  - name: vaex-longhorn
    labels: { nodegroup: vaex-longhorn }
    instanceType: m5.xlarge
    minSize: 3
    maxSize: 5
    desiredCapacity: 3
    volumeSize: 200
    ssh:
      allow: true
      publicKeyName: vaex-longhorn
    iam:
      withAddonPolicies:
        autoScaler: true
