---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaex-server
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: vaex-server
  template:
    metadata:
      labels:
        app: vaex-server
    spec:
      containers:
        - name: vaex-server
          image: anthcor/vaex-server
          ports:
            - name: vaex-server
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: 6Gi
              cpu: 2048m
          readinessProbe:
            httpGet:
              path: /
              port: vaex-server
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: vaex-server
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: VAEX_CACHE
              value: disk
            - name: VAEX_CACHE_DISK_SIZE_LIMIT
              value: 10GB
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
